version: '3'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
services:
  user-interest-service:
    build:
      context: ./user-interest-service
    ports: 
      - 3030:3030
    networks:
      - network
  image-optimization-service:
    build:
      context: ./image-optimization-service
    networks:
      - network
  mystore-front:
    build:
      context: ./mystore-front
    ports: 
      - 3000:3000
    networks:
      - network
  filter-service:
    build:
      context: ./filter-service
    ports:
      - 3131:3131
    networks:
      - network
    environment:
      - NEXT_PUBLIC_API_ENDPOINT="http://127.0.0.1:3030/api"
      - NEXT_PUBLIC_API_FILTER_ENDPOINT="http://127.0.0.1:3131/api-filter"
      - NEXT_PUBLIC_BACKEND_URL="http://127.0.0.1:3030"
    depends_on:
      - user-interest-service